import { Disk } from "../types/diskType";

//  It's temporaaly bd list for testing frontend part

export let BD_IMITATION: Array<Disk> = [
    {
        id: 1,
        name: "disk_1",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_1",
        author: "author_1",
        picture: "url_1",
        price: 1499,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1000,
    },
    {
        id: 2,
        name: "disk_2",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_2",
        author: "author_2",
        picture: "url_2",
        price: 1799,
        salePrice: -1,
        currency: "₽",
        popularityInd: 987,
    },
    {
        id: 3,
        name: "disk_3",
        description: "text about disk_! text about disk_! text about disk_! text about disk_!",
        janre: "janre_3",
        author: "author_3",
        picture: "url_3",
        price: 999,
        salePrice: -1,
        currency: "₽",
        popularityInd: 756,
    },
    {
        id: 4,
        name: "disk_4",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_4",
        author: "author_4",
        picture: "url_4",
        price: 1359,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1016,
    },
    {
        id: 5,
        name: "disk_5",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_5",
        author: "author_5",
        picture: "url_5",
        price: 1239,
        salePrice: 1099,
        currency: "₽",
        popularityInd: 1201,
    },
    {
        id: 6,
        name: "disk_6",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_6",
        author: "author_6",
        picture: "url_6",
        price: 1439,
        salePrice: 1199,
        currency: "₽",
        popularityInd: 1259,
    },
    {
        id: 7,
        name: "disk_7",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_7",
        author: "author_7",
        picture: "url_7",
        price: 949,
        salePrice: 729,
        currency: "₽",
        popularityInd: 696,
    },
    {
        id: 8,
        name: "disk_1",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_1",
        author: "author_1",
        picture: "url_1",
        price: 1499,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1000,
    },
    {
        id: 9,
        name: "disk_2",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_2",
        author: "author_2",
        picture: "url_2",
        price: 1799,
        salePrice: -1,
        currency: "₽",
        popularityInd: 987,
    },
    {
        id: 10,
        name: "disk_3",
        description: "text about disk_! text about disk_! text about disk_! text about disk_!",
        janre: "janre_3",
        author: "author_3",
        picture: "url_3",
        price: 999,
        salePrice: -1,
        currency: "₽",
        popularityInd: 756,
    },
    {
        id: 11,
        name: "disk_4",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_4",
        author: "author_4",
        picture: "url_4",
        price: 1359,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1016,
    },
    {
        id: 12,
        name: "disk_5",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_5",
        author: "author_5",
        picture: "url_5",
        price: 1239,
        salePrice: 1099,
        currency: "₽",
        popularityInd: 1201,
    },
    {
        id: 13,
        name: "disk_6",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_6",
        author: "author_6",
        picture: "url_6",
        price: 1439,
        salePrice: 1199,
        currency: "₽",
        popularityInd: 1259,
    },
    {
        id: 14,
        name: "disk_7",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_7",
        author: "author_7",
        picture: "url_7",
        price: 949,
        salePrice: 729,
        currency: "₽",
        popularityInd: 696,
    },
    {
        id: 15,
        name: "disk_1",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_1",
        author: "author_1",
        picture: "url_1",
        price: 1499,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1000,
    },
    {
        id: 16,
        name: "disk_2",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_2",
        author: "author_2",
        picture: "url_2",
        price: 1799,
        salePrice: -1,
        currency: "₽",
        popularityInd: 987,
    },
    {
        id: 17,
        name: "disk_3",
        description: "text about disk_! text about disk_! text about disk_! text about disk_!",
        janre: "janre_3",
        author: "author_3",
        picture: "url_3",
        price: 999,
        salePrice: -1,
        currency: "₽",
        popularityInd: 756,
    },
    {
        id: 18,
        name: "disk_4",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_4",
        author: "author_4",
        picture: "url_4",
        price: 1359,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1016,
    },
    {
        id: 19,
        name: "disk_5",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_5",
        author: "author_5",
        picture: "url_5",
        price: 1239,
        salePrice: 1099,
        currency: "₽",
        popularityInd: 1201,
    },
    {
        id: 20,
        name: "disk_6",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_6",
        author: "author_6",
        picture: "url_6",
        price: 1439,
        salePrice: 1199,
        currency: "₽",
        popularityInd: 1259,
    },
    {
        id: 21,
        name: "disk_7",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_7",
        author: "author_7",
        picture: "url_7",
        price: 949,
        salePrice: 729,
        currency: "₽",
        popularityInd: 696,
    },
    {
        id: 22,
        name: "disk_1",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_1",
        author: "author_1",
        picture: "url_1",
        price: 1499,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1000,
    },
    {
        id: 23,
        name: "disk_2",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_2",
        author: "author_2",
        picture: "url_2",
        price: 1799,
        salePrice: -1,
        currency: "₽",
        popularityInd: 987,
    },
    {
        id: 24,
        name: "disk_3",
        description: "text about disk_! text about disk_! text about disk_! text about disk_!",
        janre: "janre_3",
        author: "author_3",
        picture: "url_3",
        price: 999,
        salePrice: -1,
        currency: "₽",
        popularityInd: 756,
    },
    {
        id: 25,
        name: "disk_4",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_4",
        author: "author_4",
        picture: "url_4",
        price: 1359,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1016,
    },
    {
        id: 26,
        name: "disk_5",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_5",
        author: "author_5",
        picture: "url_5",
        price: 1239,
        salePrice: 1099,
        currency: "₽",
        popularityInd: 1201,
    },
    {
        id: 27,
        name: "disk_6",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_6",
        author: "author_6",
        picture: "url_6",
        price: 1439,
        salePrice: 1199,
        currency: "₽",
        popularityInd: 1259,
    },
    {
        id: 28,
        name: "disk_7",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_7",
        author: "author_7",
        picture: "url_7",
        price: 949,
        salePrice: 729,
        currency: "₽",
        popularityInd: 696,
    },
    {
        id: 29,
        name: "disk_1",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_1",
        author: "author_1",
        picture: "url_1",
        price: 1499,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1000,
    },
    {
        id: 30,
        name: "disk_2",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_2",
        author: "author_2",
        picture: "url_2",
        price: 1799,
        salePrice: -1,
        currency: "₽",
        popularityInd: 987,
    },
    {
        id: 31,
        name: "disk_3",
        description: "text about disk_! text about disk_! text about disk_! text about disk_!",
        janre: "janre_3",
        author: "author_3",
        picture: "url_3",
        price: 999,
        salePrice: -1,
        currency: "₽",
        popularityInd: 756,
    },
    {
        id: 32,
        name: "disk_4",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_4",
        author: "author_4",
        picture: "url_4",
        price: 1359,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1016,
    },
    {
        id: 33,
        name: "disk_5",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_5",
        author: "author_5",
        picture: "url_5",
        price: 1239,
        salePrice: 1099,
        currency: "₽",
        popularityInd: 1201,
    },
    {
        id: 34,
        name: "disk_6",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_6",
        author: "author_6",
        picture: "url_6",
        price: 1439,
        salePrice: 1199,
        currency: "₽",
        popularityInd: 1259,
    },
    {
        id: 35,
        name: "disk_7",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_7",
        author: "author_7",
        picture: "url_7",
        price: 949,
        salePrice: 729,
        currency: "₽",
        popularityInd: 696,
    },
    {
        id: 36,
        name: "disk_1",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_1",
        author: "author_1",
        picture: "url_1",
        price: 1499,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1000,
    },
    {
        id: 37,
        name: "disk_2",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_2",
        author: "author_2",
        picture: "url_2",
        price: 1799,
        salePrice: -1,
        currency: "₽",
        popularityInd: 987,
    },
    {
        id: 38,
        name: "disk_3",
        description: "text about disk_! text about disk_! text about disk_! text about disk_!",
        janre: "janre_3",
        author: "author_3",
        picture: "url_3",
        price: 999,
        salePrice: -1,
        currency: "₽",
        popularityInd: 756,
    },
    {
        id: 39,
        name: "disk_4",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_4",
        author: "author_4",
        picture: "url_4",
        price: 1359,
        salePrice: -1,
        currency: "₽",
        popularityInd: 1016,
    },
    {
        id: 40,
        name: "disk_5",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_5",
        author: "author_5",
        picture: "url_5",
        price: 1239,
        salePrice: 1099,
        currency: "₽",
        popularityInd: 1201,
    },
    {
        id: 41,
        name: "disk_6",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_6",
        author: "author_6",
        picture: "url_6",
        price: 1439,
        salePrice: 1199,
        currency: "₽",
        popularityInd: 1259,
    },
    {
        id: 42,
        name: "disk_7",
        description: "text about disk! text about disk! text about disk! text about disk!",
        janre: "janre_7",
        author: "author_7",
        picture: "url_7",
        price: 949,
        salePrice: 729,
        currency: "₽",
        popularityInd: 696,
    },
]