name: Frontend Ci-Cd
on: 
  push:
    paths-ignore:
      - .github/* 
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Rep clone
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Rep clone
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: lint
        run: npm run lint